### ISSUE TITLE
Is this a drop-in replacement for pug-loader?

### ISSUE THREAD

**Issue by BassOfBass** [Spence-S/simple-pug-loader#4]
Because I get a bunch of 
```sh
Module parse failed: Unterminated string constant (27:19)
  - File was processed with these loaders:
  - * ./node_modules/html-webpack-plugin/lib/loader.js
  - * ./node_modules/simple-pug-loader/index.js
  - You may need an additional loader to handle the result of these loaders.
```
thrown while using this.

**Comment by spence-s** [comment]
In some situations it will work out of the box - but its not a drop in replacement. pug-loader will attempt to inline includes I believe where as this package just uses pug. If you can make a reproducible example I am happy to help debug.

**Comment by BassOfBass** [comment]
For some reason the repro doesn't throw any errors, so I'll just show errors according to [this branch](https://github.com/BassOfBass/landing-page/tree/todo-app) (btw I am not using any `include`s, so it couldn't be the source of problems).
If you really want to look at the errors, you can clone it and run `npm install && npm run dev` in it.

- First error
```sh
> pug_html = pug_html + "\u003Cprogress" + (pug.attr("max", max, true, true)+p  ug.attr("value", value, true, true)) + "\u003E\u003Cdiv class=\"progress-bar\"  \u003E\u003Cspan" + (pug.attr("style", pug.style(`width: ${current}%`), true,   true)) + "\u003E" + (pug.escape(null == (pug_interp = current) ? "" : pug_inte  rp)) + "%
```
This I assume is [`progressBar`](https://github.com/BassOfBass/landing-page/blob/780833fdbc95579a19a01fb1ab2d9fdb1d724d26/src/templates/frontend-mentor/crowdfunding.pug#L49) mixin.
- Second error
```sh
`, true, true)+" sizes=\"(max-width: 375px) 375px,
```
This is [`srcset` string](https://github.com/BassOfBass/landing-page/blob/780833fdbc95579a19a01fb1ab2d9fdb1d724d26/src/templates/frontend-mentor/easybank/index.pug#L9).
- Third error
```sh
- |   (function (Date) {
  - >     pug_html = pug_html + "\u003C!DOCTYPE html\u003E\u003Chtml...
```
  This one is a bit long, but it looks like [`this template`](https://github.com/BassOfBass/landing-page/blob/todo-app/src/templates/test/test.pug). Judging by `(function (Date) {` at the error start it doesn't like [`new Date()` invocations](https://github.com/BassOfBass/landing-page/blob/780833fdbc95579a19a01fb1ab2d9fdb1d724d26/src/templates/test/test.pug#L120) in the template.

At first I thought at least the second error has to do something with a template literal spanning several lines, but exact same structure in [repro](https://github.com/BassOfBass/test-repo/blob/5889e68dfa05047f509f3f905c0848f16b85cf9f/src/templates/index.pug#L42) works fine. Also is there a reason these errors get duplicated 4 times?

**Comment by spence-s** [comment]
@BassOfBass thanks so much for filing the issue! I found a core bug that was causing the compiled functions to break lines inside of strings. It has nothing to do with your code. Please install version 0.1.2 by running `npm install simple-pug-loader` and retry - it should work well for you now.
